# Generated by Django 5.0.2 on 2024-02-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='text_tasks',
            new_name='enter_tasks',
        ),
    ]
