# Generated by Django 5.0.2 on 2024-02-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
