# Generated by Django 5.0.2 on 2024-02-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0004_alter_entries_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='slug',
        ),
    ]
