# Generated by Django 5.0.2 on 2024-02-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0005_remove_entries_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
